/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.WindowConstants;

/**
 *
 * @author User
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setTitle("Home");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        menuMain = new javax.swing.JMenuBar();
        mPerformer = new javax.swing.JMenu();
        miPerformerSinger = new javax.swing.JMenuItem();
        miPerformerBand = new javax.swing.JMenuItem();
        miPerformerDelete = new javax.swing.JMenuItem();
        mAlbum = new javax.swing.JMenu();
        miAlbumNew = new javax.swing.JMenuItem();
        miAlbumEdit = new javax.swing.JMenuItem();
        mSearch = new javax.swing.JMenu();
        miSearchPerformer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mPerformer.setText("Performer");

        miPerformerSinger.setText("Singer");
        miPerformerSinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPerformerSingerActionPerformed(evt);
            }
        });
        mPerformer.add(miPerformerSinger);

        miPerformerBand.setText("Band");
        mPerformer.add(miPerformerBand);

        miPerformerDelete.setText("Delete");
        mPerformer.add(miPerformerDelete);

        menuMain.add(mPerformer);

        mAlbum.setText("Album");

        miAlbumNew.setText("New");
        mAlbum.add(miAlbumNew);

        miAlbumEdit.setText("Edit");
        mAlbum.add(miAlbumEdit);

        menuMain.add(mAlbum);

        mSearch.setText("Search");

        miSearchPerformer.setText("Performer");
        mSearch.add(miSearchPerformer);

        menuMain.add(mSearch);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser)
                .addContainerGap(752, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miPerformerSingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPerformerSingerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miPerformerSingerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenu mAlbum;
    private javax.swing.JMenu mPerformer;
    private javax.swing.JMenu mSearch;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenuItem miAlbumEdit;
    private javax.swing.JMenuItem miAlbumNew;
    private javax.swing.JMenuItem miPerformerBand;
    private javax.swing.JMenuItem miPerformerDelete;
    private javax.swing.JMenuItem miPerformerSinger;
    private javax.swing.JMenuItem miSearchPerformer;
    // End of variables declaration//GEN-END:variables
   
    public JMenuItem getMiSinger() {
        return miPerformerSinger;
    }

    public JMenuItem getMiBand() {
        return miPerformerBand;
    }

    public JMenuItem getMiAlbumNew() {
        return miAlbumNew;
    }

    public JLabel getLblUser() {
        return lblUser;
    }

    public JMenuItem getMiAlbumEdit() {
        return miAlbumEdit;
    }

    public JMenuItem getMiSearchPerformer() {
        return miSearchPerformer;
    }

    public void addMiSingerActionListener(ActionListener actionListener) {
        miPerformerSinger.addActionListener(actionListener);
    }
    
    public void addMiBandActionListener(ActionListener actionListener) {
        miPerformerBand.addActionListener(actionListener);
    }
    
    public void addMiDeleteActionListener(ActionListener actionListener) {
        miPerformerDelete.addActionListener(actionListener);
    }
    
    public void addMiAlbumNewActionListener(ActionListener actionListener) {
        miAlbumNew.addActionListener(actionListener);
    }

    public void addMiAlbumEditActionListener(ActionListener actionListener) {
        miAlbumEdit.addActionListener(actionListener);
    }
    
    public void addMiSearchPerformerActionListener(ActionListener actionListener) {
        miSearchPerformer.addActionListener(actionListener);
    }

}
